### ISSUE TITLE
[Feature Request] option to preserve order of keys

### ISSUE THREAD

**Issue by andykais** [dbohdan/remarshal#11]
right now, a yaml file outputted to a json file will reorder the keys alphabetically. It would be much more readable if the outputted json kept the original order of items when it is outputted.

currently:
```
# yaml input
a: 1
c: 1
b: 1

# json output
{
  "a": 1,
  "b": 1,
  "c": 1
}
```

I have not tested it between other formats but I assume this is also true for them. The easiest way to do this would be a cli flag like `--preserve-order`

**Comment by thorstenkampe** [comment]
Will that also work for Yaml to Yaml conversions?

**Comment by dbohdan** [comment]
Done in [v0.9.0](https://github.com/dbohdan/remarshal/releases/tag/v0.9.0).
