### ISSUE TITLE
Operations before re-serialising

### ISSUE THREAD

**Issue by jayvdb** [dbohdan/remarshal#28]
Any chance of a CLI interface for performing operations after deserialisation, before re-serialisation, like `jq` , perhaps using a simpler operation syntax like [`jsonpatch`](https://pypi.org/project/jsonpatch/)

**Comment by dbohdan** [comment]
For now: no.  `jq` is nothing less than a programming language, and implementing one is out of scope for a format converter like remarshal.  It would also require a serious design effort to be pleasant to use.  If I ever rewrite remarshal from scratch, I may structure it around an embedded scripting language interpreter like [Duktape](https://duktape.org/), which would give you scripting "for free", but probably not.  There are [other tools](https://github.com/dbohdan/structured-text-tools) you can use instead.
