### ISSUE TITLE
Invalid conversion from Json array to TOML array

### ISSUE THREAD

**Issue by juouy** [dbohdan/remarshal#29]
Invalid conversion from Json array to TOML array

JSON Input file:

```
{
 "data": [1,1.7,3 ]
}
```

TOML output file:

`data = [1, 1.7, 3]`

https://www.toml-lint.com/

_3 should be of type "Float"._

Seems that toml doesn't support different data types within array. Problem is guessing what user meant with this statement and to which value it should be converted to. Reporting anyway. Great tool overall.

**Comment by dbohdan** [comment]
This is a restriction in TOML v0.4 (which is what remarshal supports).  The restriction was relaxed in later versions through https://github.com/toml-lang/toml/issues/665.  The issue will be resolved with issue #19.

> Great tool overall.

Thanks!
