### ISSUE TITLE
Have you considered homebrew for releases?

### ISSUE THREAD

**Issue by dai0304** [dbohdan/remarshal#3]
http://stackoverflow.com/questions/27097005/how-to-package-go-project-for-homebrew

**Comment by dbohdan** [comment]
I don't run OS X any more, so I would not have a convenient way to test a Homebrew release of Remarshal. If you use Remarshal on OS X why not contribute a Formula for it to Homebrew yourself? You would be able to test it and ensure it works correctly. If you have any questions about Remarshal in the process I will do my best to answer them.

**Comment by dai0304** [comment]
OK.  It's done!
https://github.com/Homebrew/homebrew/pull/39104

**Comment by dbohdan** [comment]
@dai0304 Great!
